const quotes = [
  '"A vida é 10% o que acontece comigo e 90% como eu reajo a isso."',
  '"O sucesso é ir de fracasso em fracasso sem perder o entusiasmo."',
  '"A única maneira de fazer um excelente trabalho é amar o que você faz."',
  '"A imaginação é mais importante que o conhecimento."',
  '"A felicidade não é algo pronto. Ela vem das suas próprias ações."',
  '"A vida é aquilo que acontece enquanto você está ocupado fazendo outros planos."',
  '"Seja a mudança que você quer ver no mundo."',
  '"Não espere por oportunidades extraordinárias. Agarre ocasiões comuns e torne-as grandes."',
  '"A persistência realiza o impossível."',
  '"A melhor maneira de prever o futuro é criá-lo."',
  '"A simplicidade é o último grau da sofisticação."',
  '"O conhecimento é a chave para a liberdade."',
  '"A coragem é a resistência ao medo, o domínio do medo, e não a ausência dele."',
  '"O que não nos mata nos torna mais fortes."',
  '"Não importa o quão devagar você vá, desde que você não pare."',
  '"A vida é feita de escolhas, e cada escolha molda o seu destino."',
  '"A esperança é a última que morre, mas é a primeira que precisa viver."',
  '"O otimismo é a fé que leva à realização."',
  '"A maior glória em viver não está em nunca cair, mas em se levantar toda vez que caímos."',
  '"A paciência é amarga, mas seu fruto é doce."',
  '"A liberdade começa onde termina o medo."',
  '"O sucesso nasce do querer, da determinação e da persistência."',
  '"A vida é curta demais para ser pequena."',
  '"O tempo é o recurso mais valioso que temos, use-o com sabedoria."',
  '"Quem olha para fora, sonha; quem olha para dentro, desperta."',
  '"Não podemos ajudar todos, mas todos podem ajudar alguém."',
  '"Nunca é tarde demais para ser o que você poderia ter sido."',
  '"A humildade é o fundamento de todas as virtudes."',
  '"O fracasso é apenas a oportunidade de recomeçar com mais inteligência."',
  '"Não tenha medo da perfeição — você nunca a alcançará."',
  '"A criatividade é a inteligência se divertindo."',
  '"O segredo da felicidade não é fazer o que se gosta, mas gostar do que se faz."',
  '"A dúvida é o começo da sabedoria."',
  '"O importante não é vencer todos os dias, mas lutar sempre."',
  '"Sonhar grande e sonhar pequeno dá o mesmo trabalho."',
  '"A jornada é mais importante do que o destino."',
  '"Você nunca será velho demais para definir uma nova meta ou sonhar um novo sonho."',
  '"A força não vem da capacidade física, mas de uma vontade indomável."',
  '"Não existe caminho para a felicidade. A felicidade é o caminho."',
  '"A vida é uma peça de teatro que não permite ensaios."',
  '"Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser."',
  '"A maior prisão que as pessoas vivem é o medo do que os outros vão pensar."',
  '"Se você quer resultados diferentes, faça algo diferente."',
  '"O segredo do sucesso é começar antes de estar pronto."',
  '"A disciplina é a ponte entre metas e realizações."',
  '"O maior erro que você pode cometer é o de ficar o tempo todo com medo de errar."',
  '"Grandes coisas nunca vêm de zonas de conforto."',
  '"Não conte os dias, faça os dias contarem."',
  '"Você é o único responsável por escrever a sua própria história."',
  '"A melhor forma de prever o futuro é criá-lo."'
];
